### ISSUE TITLE
Add free software LICENSE

### ISSUE THREAD

**Issue by siraben** [wucke13/nix-autobahn#39]
As noted in https://github.com/NixOS/nixpkgs/issues/145015, the absence of a license implies that the project is non-free. It would be great if a free software license such as MIT or GPLv3 were added to the repository.

**Comment by cole-h** [comment]
There is a license though? https://github.com/wucke13/nix-autobahn/blob/master/LICENSE

**Comment by siraben** [comment]
Disregard, I should have read the repo! 😂
